### ISSUE TITLE
Option to generate bibtex from other sources DBPL

### ISSUE THREAD

**Issue by dinhanhx** [vict0rsch/PaperMemory#112]
An option to generate bibtex from Google Scholar, Semantic Scholar. 

For example, one click https://arxiv.org/abs/1602.07261 

Instead of showing this
![image](https://user-images.githubusercontent.com/38489776/181902768-52e4119e-4888-4441-8317-23dbd06e3352.png)
It can show this
```
@article{szegedy2016inception,
  title={Inception-v4, inception-resnet and the impact of residual connections on learning (2016)},
  author={Szegedy, Christian and Ioffe, Sergey and Vanhoucke, Vincent and Alemi, Alex},
  journal={arXiv preprint arXiv:1602.07261},
  year={2016},
  publisher={CoRR}
}
```

**Comment by vict0rsch** [comment]
That's not really how it works. First of all, you should almost certainly not use an Arxiv preprint citation when a proper publication citation is available.

But more importantly, not all sources have the same data and I cannot guarantee a choice in citation sources. The way it currently works is it sequentially queries the sources (PapersWithCide, then Semantic Scholar, then DBLP, then GS) and the first one that has a publication match for the preprint displays the bibtex.

Having an option to choose sources would be a nightmare in UI because they all have varying latencies and you'd have to wait for _all_ sources to respond before having your citation instead of getting it with the first to respond.

I'll keep your suggestion in mind though.

If you think it's a big deal, keep this issue open. If you think it's not, then you can close it.

In any case, thank you for taking the time to improve PaperMemory!

**Comment by vict0rsch** [comment]
I've reordered preprint matching sources so that DBLP is last and therefore if you _do_ see a DBLP citation there it means others have failed

(in #117 so next release)
