### ISSUE TITLE
Add some features (filter, switch for venues ...)

### ISSUE THREAD

**Issue by kaixin96** [vict0rsch/PaperMemory#61]
Thank you very much @vict0rsch! I feel very lucky to come across this project. I was relying on [my forked project](https://github.com/kaixin96/auto_arxiv_bookmarker) to store visited papers as bookmarks. But recently it doesn't work somehow (probably due to manifest v2 -> v3 migration). Your project is a LIFESAVER !!!

Based on my experience, I believe these features can be useful:

- A switch for each venue in the setting page (e.g., only record arxiv and openreview papers)
- Filter the search results by year/month 
- Helper message when hovering on the icon (copy link, download etc.)
- A switch that allows storing papers only happens when PDF is opened (because a lot of time, we don't really want to save a paper after scanning its abstract)

Thank you! And by the way, do you have a buymeacoffee link? I am happy to support.

**Comment by kaixin96** [comment]
The first feature "A switch for each venue in the setting page" is already shipped with Chrome (in the extension setting page).

**Comment by vict0rsch** [comment]
Hey! It's great to read that. It's truly heartwarming :) 

Thank you for your suggestion. There's an upcoming version in #60 I'll add those features:

1. I'll add that to the options page
2. Are you talking about the paper's publication/upload date? In that case I can add a `y:<year>` search filter just like there are `t:<tag>` and `c:<code>` filters already. I don't want to change the UI too much it would become too crowded...
3. They are supposed to be there as `title=` but I realized there are some build issues it'll be fixed in the upcoming `v0.5.0`
4. That can be done indeed in the popup's menu

I didn't have a buymyacoffee link until you suggested it. It's going to be on the readme. Really the things you can do to best support me is share the project and keep helping be with improvement suggestions and bug reports! 

Thanks again 😃

**Comment by kaixin96** [comment]
Thank you for the reply.

1) I find it is possible to switch off the venues via setting site access in extension's detail page. So you don't have to implement that.
2) A `y:<year>` would suffice. I agree it is better to keep a simple UI.

I will definitely recommend this to my friends/colleagues. Speaking of suggestions, I find that this might be quite useful: opening the memory bank in a new tab (or in full screen mode), such that we can see more entries in a screen.

Thank you :)

**Comment by vict0rsch** [comment]
1. It won't be possible to do that in the next release. I will add a new permission for `<all_urls>`. This is required otherwise every time I add a paper source, it's associated with a new permission request which automatically disables the extension on user browsers... So I added your suggestion in the advanced options page in the next release
2. I've implemented `y: year` and also `y: <year` for papers _before_ `year` and `y: >year` for paper _after_ (strictly) `year`
3. 
4. It's not _already_ in the menu but I did add it in the next release
5. There will also be a full-page memory page in the next release :)

**Comment by kaixin96** [comment]
Thank you for the reply. Can't wait to see the next release :)

**Comment by kaixin96** [comment]
Sure, no problem! I will update the issues I find in this thread. Thanks :)

**Comment by vict0rsch** [comment]
Indeed there was a typo, it should be fixed if you pull

**Comment by vict0rsch** [comment]
Indeed there was a typo, it should be fixed if you pull

**Comment by vict0rsch** [comment]
Hey @kaixin96! Have you tested the new features? Do you think it's ready? I'm thinking of releasing next week

**Comment by kaixin96** [comment]
Yes, I have tested the new features and I think it's ready for release.

**Comment by vict0rsch** [comment]
It's all released!

**Comment by kaixin96** [comment]
Nice!
